version: '3'
services:
  redis:
    image: redis:latest
    container_name: redis-container
    ports:
      - "6379:6379"
    networks:
      - spring-redis-net

  theaketing-1:
    image: localhost:5000/theaketing
    container_name: theaketing-1
    depends_on:
      - redis
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      SPRING_DATA_REDIS_HOST: redis-container
    ports:
      - "9000:9000"
    networks:
      - spring-redis-net

  theaketing-2:
    image: localhost:5000/theaketing
    container_name: theaketing-2
    depends_on:
      - redis
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      SPRING_DATA_REDIS_HOST: redis-container
    ports:
      - "9001:9000"
    networks:
      - spring-redis-net

networks:
  spring-redis-net:
    driver: bridge